public void testCheckUserExistsException() throws Exception {
    try {
        evilDAO.checkUserExists(0L);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}