public void testEvilDatabase() {
    try {
        action = new EditOfficeVisitAction(EvilDAOFactory.getEvilInstance(), 0L, "1", "1");
        fail("exception should have been thrown");
    } catch (iTrustException e) {
        assertEquals("A database exception has occurred. Please see the log in the console for stacktrace", e.getMessage());
        DBException dbe = ((DBException) (e));
        assertEquals(EvilDAOFactory.MESSAGE, dbe.getSQLException().getMessage());
    }
}