public void testRecordLoginFailureEvil() throws Exception {
    action = new LoginFailureAction(evil, "192.168.1.1");
    assertEquals(("A database exception has occurred. Please see the log in the " + "console for stacktrace"), action.recordLoginFailure());
}